from projectapp.tests.test_common import BaseProjectWebTest
from projectapp.tests.test_detail_project import DetailProjectTest
from projectapp.tests.test_edit_project import EditProjectTest
from projectapp.tests.test_main_page import MainPageTest
from projectapp.tests.test_my_project_list import MyProjectListTest
from projectapp.tests.test_new_project import NewProjectTest
from projectapp.tests.test_search_project  import SearchProjectTest