# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 01:36
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.hashers import make_password


def load_users(apps, schema_editor):
	UserApp = apps.get_model("authapp", "User")
	
	app_user = UserApp(
    	username="hernan.hernandez@email.com", 
    	first_name="Hernan",
    	last_name="Hernandez",
    	email="hernan.hernandez@email.com", 
    	password=make_password('idea123'), 
    	is_active=True,
    	country = "Chile",
		company = "Company Inc."
    )
	app_user.save()
	app_user = UserApp(
		username="barbara.barrera@email.com", 
		first_name="Barbara",
		last_name="Barrera",
		email="barbara.barrera@email.com", 
		password=make_password('idea123'), 
		is_active=True,
		country = "Peru",
		company = "None S.A."
	)
	app_user.save()
	app_user = UserApp(
		username="pedro.pedrero@email.com", 
		first_name="Pedro",
		last_name="Pedrero",
		email="pedro.pedrero@email.com", 
		password=make_password('idea123'), 
		is_active=True,
		country = "Chile",
		company = "Compañia S.A"
	)
	app_user.save()
	app_user = UserApp(
		username="jimena.jimenez@email.com", 
		first_name="Jimena",
		last_name="Jimenez",
		email="jimena.jimenez@email.com", 
		password=make_password('idea123'), 
		is_active=True,
		country = "Argentina",
		company = "Inc. S.A."
	)
	app_user.save()		



class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(load_users),
    ]
