# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('advantages', models.TextField()),
                ('investment', models.CharField(choices=[('< 100 USD', '< 100 USD'), ('100 - 300 USD', '100 - 300 USD'), ('301 - 500 USD', '301 - 500 USD'), ('501 - 800 USD', '501 - 800 USD'), ('801 - 1000 USD', '801 - 1000 USD'), ('> 1000 USD', '> 1000 USD')], max_length=100)),
                ('date_creation', models.DateField()),
                ('date_last_modification', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('project', models.ManyToManyField(to='projectapp.Project')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.Project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.User'),
        ),
    ]
