# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_last_modification',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='investment',
            field=models.CharField(choices=[('< $100 USD', '< $100 USD'), ('$100 - $300 USD', '$100 - $300 USD'), ('$301 - $500 USD', '$301 - $500 USD'), ('$501 - $800 USD', '$501 - $800 USD'), ('$801 - $1000 USD', '$801 - $1000 USD'), ('> $1000 USD', '> $1000 USD')], max_length=100),
        ),
    ]
