# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20170219_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='projectapp.Tag'),
        ),
    ]
