# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20170220_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
