# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_auto_20170320_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publication_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
