# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 01:45
from __future__ import unicode_literals

from django.db import migrations



def load_tags(apps, schema_editor):
		Tag = apps.get_model("projectapp", "Tag")
		db_alias = schema_editor.connection.alias
		Tag.objects.using(db_alias).bulk_create(\
    	[  
	    	Tag(tag="USA"),
	        Tag(tag="lush"),
			Tag(tag="possessive"),
			Tag(tag="wary"),
			Tag(tag="suit"),
			Tag(tag="berry"),
			Tag(tag="crown"),
			Tag(tag="sock"),
			Tag(tag="maid"),
			Tag(tag="vacation"),
			Tag(tag="steam"),
			Tag(tag="bomb"),
			Tag(tag="end"),
			Tag(tag="afterthought"),
			Tag(tag="development"),
			Tag(tag="futuristic"),
			Tag(tag="shallow"),
			Tag(tag="hurry"),
			Tag(tag="increase"),
			Tag(tag="typical"),
			Tag(tag="jeans"),
			Tag(tag="various"),
			Tag(tag="troubled"),
			Tag(tag="nose"),
			Tag(tag="grape"),
			Tag(tag="year"),
			Tag(tag="start"),
			Tag(tag="suit"),
			Tag(tag="paltry"),
			Tag(tag="slap"),
			Tag(tag="shiny"),
			Tag(tag="minister"),
			Tag(tag="statuesque"),
			Tag(tag="abaft"),
			Tag(tag="spill"),
			Tag(tag="play"),
			Tag(tag="complex"),
			Tag(tag="remain"),
			Tag(tag="club"),
			Tag(tag="glamorous"),
			Tag(tag="snatch"),
			Tag(tag="outrageous"),
			Tag(tag="fantastic"),
			Tag(tag="smile"),
			Tag(tag="religion"),
			Tag(tag="texture"),
			Tag(tag="dramatic"),
			Tag(tag="well-made"),
			Tag(tag="title"),
			Tag(tag="damage"),
			Tag(tag="pig"),
	    ]
	)

class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_auto_20170331_0247'),
    ]

    operations = [
    	migrations.RunPython(load_tags),
    ]
