# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 01:29
from __future__ import unicode_literals
from django.db import migrations


import random

def load_comments(apps, schema_editor):
	Project = apps.get_model("projectapp", "Project")
	Comment = apps.get_model("projectapp", "Comment")
	User = apps.get_model("authapp", "User")

	users = User.objects.all()
	projects = Project.objects.all()


	for x in range(0, 50):
		app_comment = Comment(
			user = users[random.randint(0, 3)],
			project = projects[random.randint(0, 24)] ,
			score = random.randint(0, 5),
			comment = "Interdum et malesuada, fames ac ante ipsum primis in faucibus. Sed eu ullamcorper dolor"
		)
		app_comment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_auto_20170707_2328'),
    ]

    operations = [
    	migrations.RunPython(load_comments),
    ]
