# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_auto_20170717_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='added_to_project',
            field=models.BooleanField(default=False),
        ),
    ]
